export const data = [
  { value: "7", action: "CONCAT" },
  { value: "8", action: "CONCAT" },
  { value: "9", action: "CONCAT" },
  { value: "DEL", action: "DELETE" },
  { value: "4", action: "CONCAT" },
  { value: "5", action: "CONCAT" },
  { value: "6", action: "CONCAT" },
  { value: "+", action: "CALCULATE" },
  { value: "1", action: "CONCAT" },
  { value: "2", action: "CONCAT" },
  { value: "3", action: "CONCAT" },
  { value: "-", action: "CALCULATE" },
  { value: ".", action: "CONCAT" },
  { value: "0", action: "CONCAT" },
  { value: "/", action: "CALCULATE" },
  { value: "x", action: "CALCULATE" },
  { value: "RESET", action: "RESET" },
  { value: "=", action: "CALCULATE" },
];
