export const data = [
  { value: "7", type: "CONCAT" },
  { value: "8", type: "CONCAT" },
  { value: "9", type: "CONCAT" },
  { value: "DEL", type: "DELETE" },
  { value: "4", type: "CONCAT" },
  { value: "5", type: "CONCAT" },
  { value: "6", type: "CONCAT" },
  { value: "+", type: "ADD" },
  { value: "1", type: "CONCAT" },
  { value: "2", type: "CONCAT" },
  { value: "3", type: "CONCAT" },
  { value: "-", type: "SUB" },
  { value: ".", type: "CONCAT" },
  { value: "0", type: "CONCAT" },
  { value: "/", type: "DIVIDE" },
  { value: "x", type: "MULTIPLY" },
  { value: "RESET", type: "RESET" },
  { value: "=", type: "RESULT" },
];
